"""Initial migration

Revision ID: 96a43624254a
Revises:
Create Date: 2025-11-30 20:22:50.223710

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "96a43624254a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "type", sa.Enum("SYNC", "DOWNLOAD", "SCAN", name="jobtype"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", name="jobstatus"),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("logs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_repo",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vendor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("REGISTERED", "SYNCED", "ERROR", name="repostatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_repo_repo_id"), "model_repo", ["repo_id"], unique=True
    )
    op.create_table(
        "model_artifact",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model_repo_id", sa.Uuid(), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "file_type",
            sa.Enum("MODEL", "CONFIG", "TOKENIZER", "OTHER", name="artifacttype"),
            nullable=False,
        ),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "download_status",
            sa.Enum(
                "PENDING", "DOWNLOADING", "COMPLETED", "FAILED", name="downloadstatus"
            ),
            nullable=False,
        ),
        sa.Column("local_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_repo_id"],
            ["model_repo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_artifact")
    op.drop_index(op.f("ix_model_repo_repo_id"), table_name="model_repo")
    op.drop_table("model_repo")
    op.drop_table("job")
    # ### end Alembic commands ###
